### ISSUE TITLE
Newest version throws error on match()

### ISSUE THREAD

**Issue by elainevdw** [JoshBarr/on-media-query#14]
When I try running the most recent package's index file, none of the callbacks fire and I get this error on line 98, where there's a .match() function: 

Uncaught TypeError: Object #<Object> has no method 'match' 

It appears to work fine if I roll the .js file back a couple versions, where there is no .match(). 

Now, back to trying to get my site to work in IE8! lol. :)

**Comment by mhulse** [comment]
Howdy, could you throw up some test code on [jsbin.com](http://jsbin.com/)? I personally have not had any issues, but I'd like to see your code to check if you've found a corner case that we haven't thought of testing. :8ball:

**Comment by erichomanchuk** [comment]
Have the same issue.  I am just trying the demo that is supplied and there is an error, query_object.match is not a function and there appears to be no match() method in the js file.

**Comment by mhulse** [comment]
Hi,

Yah, I don't think the demo was updated to meet the latest changes to the JS file (i.e. the demo is still using the old `callback` syntax). 

If you are feeling up to it, you could do a pull request to fix the syntax in the demo or someone else (more familular with the code) can get to it when they have the free time.

If you can't do a pull request, maybe you could fix the demo on your local machine, test that with the latest JS, and then report back if you are still having issues? It should just be a simple matter of changing `callback` to `match` in the `queries` array's objects.

M

**Comment by mhulse** [comment]
I think #15 fixes this issue. Closing.
