### ISSUE TITLE
Change repo name to on-media-query (new)

### ISSUE THREAD

**Issue by mhulse** [JoshBarr/on-media-query#17]
Via @patocallaghan, his idea is probably the way I'd do it:

> Re: the repo name change, what about doing the reverse of what I suggested earlier? If you really wanted to change the name, rename this repo to on-media-query as before, this means you retain forks, commit history and followers etc....js-media-queries will then 404 but to fix that create a new repo called js-media-queries and just have a README.md which points to the new on-media-query repo..you then retain all your history etc and the 404 issue is somewhat solved....

Closing #12. It's the same issue, just there's a ton of unrelated comments (made by me) and I thought this issue still deserved some attention.

**Comment by patocallaghan** [comment]
@JoshBarr if you still wanted to rename this project Github are now doing [repo redirects](https://github.com/blog/1508-repository-redirects-are-here)

**Comment by mhulse** [comment]
That's cool! I'm glad they finally added redirects. :+1:

**Comment by JoshBarr** [comment]
Done!
