### ISSUE TITLE
usage as function?

### ISSUE THREAD

**Issue by Micsi** [JoshBarr/on-media-query#9]
Hi,

is it possible to use this in a procedural way? I want to check what context I am in in the header area of a page to generate a specified header. So that's not a callback event but a rather basic function call.

How would one do this?

**Comment by mhulse** [comment]
@Micsi Probably the only way you can get what you're looking for is to:

``` js
MQ.init(queries);
console.log('the current media query context:', MQ.new_context);
```

... Alternatively, you could write your own JS function to get the current context. Something like:

``` js
/**
 * Get the font-family style value of the passed element's style.
 *
 * @return { string } Value or empty string.
 */

function _fontFamily(el) {

    if (el) {

        // return (IE browser?) ? (Return IE fontFamily) : ((W3C browser?) ? (Return W3C font-family) : Return empty string);
        return (el.currentStyle) ? el.currentStyle['fontFamily'] : ((window.getComputedStyle) ? window.getComputedStyle(el).getPropertyValue('font-family') : '');

    }

};

//--------------------------------------------------------------------

/**
 * Get the :after content value of from the passed element's style.
 *
 * @return { string } Value or empty string.
 */

function _contentAfter(el) {

    if (el) {

        return (window.getComputedStyle) ? window.getComputedStyle(el, ':after').getPropertyValue('content') : ''; // getPropertyValue() Returns an empty string in Firefox and Opera and null in Google Chrome and Safari.

    }

};
```

... call like so:

``` js
var context = _contentAfter(document.body) || _fontFamily(document.documentElement);
context = context.replace(/['",]/g, '');
// do stuff with context ...
```

Lastly, I'm [working on a fork](https://github.com/registerguard/js-media-queries) where one could say:

``` js
var context = oMQ.getContext();
```

... without having to initialize anything. Basically, I'm using the code you see above.

FYI: I haven't pushed my local code to the `develop` branch yet, but I should have a new version pushed in the next day or so.

Hope that helps!

Micky

**Comment by mhulse** [comment]
Seems resolved to me. Closed.
